# Generated by Django 3.0.7 on 2020-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="the user can access the admin"
            ),
        ),
    ]
