# Generated by Django 3.0.5 on 2020-05-07 02:47

from django.db import migrations, models


def set_application_type_to_default(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    for application in Application.objects.all():
        application.type = Application.type.field.default
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="type",
            field=models.CharField(
                choices=[("finaid", "Financial Aid"), ("scholarship", "Scholarship")],
                default="scholarship",
                max_length=11,
            ),
        ),
        migrations.RunPython(
            set_application_type_to_default, reverse_code=migrations.RunPython.noop
        ),
    ]
