repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
        files: requirements\.in$
      - id: trailing-whitespace
  - repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      - id: pip-compile
        name: Compile requirements
      - id: pip-compile
        name: Compile development requirements
        files: ^dev-requirements.(in|txt)$
        pass_filenames: false
        args: ["dev-requirements.in"]
      - id: pip-compile
        name: Compile test requirements
        files: ^test-requirements.(in|txt)$
        pass_filenames: false
        args: ["test-requirements.in"]
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: ['--application-directories=src']
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8_bugbear
            # Our primary use case for flake8-per-file-ignores is to catch
            # unused NOQA comments.
          - flake8-per-file-ignores
