# type: ignore
"""add user roles

Revision ID: 608745cde22e
Revises: ad30ecc5b6d1
Create Date: 2020-03-20 01:52:50.472940

"""
from alembic import op
import citext
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "608745cde22e"
down_revision = "ad30ecc5b6d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", citext.CIText(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.Column("modified", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
