# type: ignore
"""initial migration

Revision ID: ad30ecc5b6d1
Revises:
Create Date: 2020-03-08 00:40:50.181386

"""
from alembic import op
import citext
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ad30ecc5b6d1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", citext.CIText(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.Column("modified", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
