# Generated by Django 3.0.5 on 2020-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="lodging_requested",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="travel_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
